CREATE DATABASE Etiquetas4
GO

USE Etiquetas4
GO

CREATE TABLE Pais(
    IdPais INT IDENTITY PRIMARY KEY,
    Pais VARCHAR(50)
)
GO

CREATE TABLE Estado(
    IdEstado INT IDENTITY PRIMARY KEY,
    Estado VARCHAR(50),
    IdPais INT FOREIGN KEY REFERENCES Pais(IdPais)
)
GO
CREATE TABLE Municipio(
    IdMunicipio INT IDENTITY PRIMARY KEY,
    Municipio VARCHAR(50),
    IdEstado INT FOREIGN KEY REFERENCES Estado(IdEstado)
)
GO

CREATE TABLE Direccion(
    IdDireccion INT IDENTITY PRIMARY KEY,
    Direccion VARCHAR(100),
    IdMunicipio INT FOREIGN KEY REFERENCES Municipio(IdMunicipio)
)
GO

CREATE TABLE Viñedo(
    IdViñedo INT ,
    Nombre  VARCHAR(50) ,
    IdDireccion INT FOREIGN KEY REFERENCES Direccion(IdDireccion),
    Descripcion VARCHAR(500) ,
    Liga VARCHAR(50),
    CONSTRAINT PK_Viñedo PRIMARY KEY(IdViñedo)
)
GO

CREATE TABLE Uva(
IdUva INT NOT NULL IDENTITY,
Uva VARCHAR(60) NOT NULL,
Color VARCHAR(50) NOT NULL,
CONSTRAINT PK_UVA PRIMARY KEY(IdUva)
);
GO

CREATE TABLE Categoria(
IdCategoria INT NOT NULL IDENTITY,
Categoria VARCHAR(50) NOT NULL UNIQUE,
CONSTRAINT PK_Categoria PRIMARY KEY(IdCategoria),
);
GO

CREATE TABLE Cata(
IdCata INT NOT NULL IDENTITY,
Vista TEXT NOT NULL,
Boca TEXT NOT NULL,
Nariz TEXT NOT NULL,
Maridaje TEXT NOT NULL,
CONSTRAINT PK_Cata PRIMARY KEY(IdCata),
);
GO

CREATE TABLE Vino(
IdVino int not null IDENTITY,
IdViñedo INT NOT NULL,
IdCategoria INT NOT NULL,
IdCata INT NOT NULL UNIQUE,
Vino VARCHAR(50) NOT NULL,
Crianza VARCHAR(35),
Añejamiento VARCHAR(55), 
Temperatura VARCHAR(35),
CONSTRAINT PK_Vinos PRIMARY KEY(IdVino),
CONSTRAINT FK_VinosToViñedos FOREIGN KEY(IdViñedo) REFERENCES Viñedo(IdViñedo) ON DELETE CASCADE,
CONSTRAINT FK_VinosToCategoria FOREIGN KEY(IdCategoria) REFERENCES Categoria(IdCategoria) ON DELETE CASCADE,
CONSTRAINT FK_VinosToCata FOREIGN KEY(IdCata) REFERENCES Cata(IdCata) ON DELETE CASCADE
);
GO

CREATE TABLE VinoUva(
IdVinoUva INT NOT NULL IDENTITY,
IdVino INT NOT NULL,
IdUva INT NOT NULL,
CONSTRAINT PK_VinoUva PRIMARY KEY(IdVinoUva),
CONSTRAINT FK_VinoUvaToVino FOREIGN KEY(IdVino) REFERENCES Vino(IdVino) ON DELETE CASCADE,
CONSTRAINT FK_VinoUvaToUva FOREIGN KEY(IdUva) REFERENCES Uva(IdUva) ON DELETE CASCADE
);
GO